In [1]:
import numpy as np


In [3]:
arr3=np.array([1,2.3,4,5,6])
print(arr3)

[1.  2.3 4.  5.  6. ]


In [5]:
arr7=np.arange(30).reshape(5,6)
print(arr7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [6]:
arr3=np.ones((2,3))
print(arr3)


[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr5=arr3.ravel()
print(arr5)

[1. 1. 1. 1. 1. 1.]


In [9]:
arr9=np.arange(27).reshape(3,3,3)
print(arr9)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [11]:
#mathematical operation
np.max(arr9)
np.min(arr9)
np.sum(arr9)
np.mean(arr9)
np.median(arr9)
np.var(arr9)
np.std(arr9)

np.float64(7.788880963698615)

In [ ]:

# create a dictionary of number and their 






SyntaxError: invalid syntax (1032088505.py, line 2)

In [8]:
fruits=["apple","mango", "graps"]
fruit_len=(len(fruits)for fruits in fruits)
print(list(fruit_len))


[5, 5, 5]
